name: Commit Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: backend # Optional: Checks out the code into a specific directory within the runner

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
        working-directory: ./backend # Specifies the working directory for this step

      - name: Install Dependencies
        run: npm install
       working-directory: ./Backend
            