name: Main Workflow

on:
  push:
    branches:
      - main

      


  build-and-test-react:
    needs: build-and-test-node
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies (React App)
        run: npm install
        working-directory: ./admin # Replace with your React app directory path
      - name: Run tests (React App)
        run: npm test
        working-directory: ./admin # Replace with your React app directory path
      - name: Build (React App)
        run: npm run build
        working-directory: ./admin # Replace with your React app directory path

  check-expo-app:
    needs: build-and-test-react
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install expo-cli
        run: npm install -g expo-cli
      - name: Install dependencies (Expo App)
        run: npm install
        working-directory: ./studyroom # Replace with your Expo app directory path
      - name: Check Expo project files
        run: expo doctor
        working-directory: ./studyroom # Replace with your Expo app directory path
  jobs:
    build-and-test-node:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Use Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '20'
        - name: Install dependencies (Server)
          run: npm install --legacu-peer-deps
          working-directory: ./Backend # Replace with your server directory path
        - name: Run tests (Server)
          run: npm test
          working-directory: ./Backend # Replace with your server directory path
