name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  # Build and Test Node.js application (should be first)
  build-and-test-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies (Server)
        run: npm install --legacy-peer-deps  # Consider using npm ci for production builds
        working-directory: ./backend  # Replace with your server directory path
     

  # Build and Test React application (depends on Node.js build)
  build-and-test-react:
    needs: build-and-test-node  # This job depends on the previous one finishing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies (React App)
        run: npm install
        working-directory: ./admin  # Replace with your React app directory path
   

      - name: Build (React App)
        run: npm run build
        working-directory: ./admin  # Replace with your React app directory path

  # Check Expo app (can potentially be independent)
  check-expo-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install expo-cli
        run: npm install -g expo-cli
      - name: Install dependencies (Expo App)
        run: npm install
        working-directory: ./studyroom  # Replace with your Expo app directory path
      - name: Check Expo project files
        run: expo doctor
        working-directory: ./studyroom  # Replace with your Expo app directory path
